### ISSUE TITLE
thread 'main' panicked at 'Unable to open cache file!: Os { code: 24, kind: Other, message: "Too many open files" }', src/platforms.rs:37:53

### ISSUE THREAD

**Issue by gprime31** [TheBinitGhimire/NtHiM#12] opened 2022-01-03 01:08 UTC
thread 'main' panicked at 'Unable to open cache file!: Os { code: 24, kind: Other, message: "Too many open files" }', src/platforms.rs:37:53

when 100+ subs in a file.

**Comment by TheBinitGhimire** [comment] 2022-01-03 06:05
Hello @gprime31,

Can I know what's the command you used while you got this error message? Are you using the project's in-built mechanism to load the file (_i.e. using the **-f** flag_), or are you using some sort of technique that depends on the system/shell you are running on?

I couldn't reproduce the issue with the project's in-built file loading mechanism (*I tried with files containing hundreds and thousands of hostnames*), so please let me know how you landed up on this error message, as that would help me out in understanding this issue well, before coming up with a fix.

Thanks,
@TheBinitGhimire

**Comment by gprime31** [comment] 2022-01-03 06:22
NtHiM -f subs.txt -o results.txt
Subs.txt contains https://example.com 
https://sub.example.com etc no params or anything.
It also seems to hang on subs that don't resolve or take too long, ex Chinese sites link sub.example.cn.

**Comment by gprime31** [comment] 2022-01-03 06:23
Is is ubuntu and zsh for shell
Thanks
Works great on most lists.

**Comment by TheBinitGhimire** [comment] 2022-01-03 08:36
Hi there,

Can you please try using the verbose (**-v**) flag to check for the non-resolving hostnames? By default, non-resolving ones aren't shown in the output, so I would like to know if it really hangs or at least displays an immediate output in verbose mode for such hostnames?

Till then, I'm looking up on your major issue, thanks for providing all the environment details! 😇😇

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment] 2022-01-03 08:47
Also, can you please try changing the value of system-wide kernel directives for maximum number of open files? But, before doing so, I'd love to know what your current limit is (_use `cat /proc/sys/fs/file-max` for that purpose_).

Here's a sample command if you would like to try changing the limit (put limit higher than existing):

```sh
sysctl -w fs.file-max=809600
````

Please let me know if this solves your issue, so that I could work on this issue further!

**Comment by gprime31** [comment] 2022-01-03 15:59
![2022-01-03_10-58](https://user-images.githubusercontent.com/44535257/147952034-d5848fe3-c8a2-4b60-82b1-b5ee2da92953.png)

**Comment by gprime31** [comment] 2022-01-03 16:01
I have ran tools that take 100's of subs as stdin and never ran into this problem, so don't really want to change os configs.
I wonder if it's rust problem?
Go and python have no problems parcing that same file all at once.

**Comment by gprime31** [comment] 2022-01-03 16:06
but I used to run this https://github.com/LukaSikic/subzy for subtakeover.
And it takes the same list and works no problem. no crashes or hangs.
but it's old.
and I like yours better :)

**Comment by gprime31** [comment] 2022-01-03 16:09
oh and for the verbose:
it just says [ERROR] An error occured for [site.com]

**Comment by TheBinitGhimire** [comment] 2022-01-04 07:17
Hi there,

Thanks for providing all of the information, and also thanks for the suggestion on that new ability! I will be working on the two flags you mentioned (i.e. **max-retries** and **timeout**).

I am still working on the major issue you are facing, regarding the file opening thing. I will put up any information or fixes here in the comments if I am able to confirm.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment] 2022-01-21 02:55
Hello @gprime31,

The new release of **NtHiM**, i.e. [**v0.1.4**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.4), is published now, which includes both of the things you mentioned here:
* Main Fix for your "_Too many open files_" issue, and
* Implementation of the **timeout** (**`-s`** or **`--timeout`**) flag!

I hope you would test these functionalities in the new version of **NtHiM**.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment] 2022-01-21 03:00
Hello @gprime31,

The new release of **NtHiM**, i.e. [**v0.1.4**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.4), is published now, which includes both of the things you mentioned here:
* Main Fix for your "_Too many open files_" issue, and,
* Implementation of the **timeout** (**`-s`** or **`--timeout`**) flag!

I hope you would test these functionalities in the new version of **NtHiM**.

Thanks,
@TheBinitGhimire

**Comment by gprime31** [comment] 2022-01-21 13:30
Works great now!!! Thanks
had to update rust to latest to compile from source, may want to add it to the install notes.
https://www.rust-lang.org/tools/install

**Comment by TheBinitGhimire** [comment] 2022-01-21 19:14
Hello @gprime31,

Thank you for your review on the new release! I feel really good to hear that it is working fine now.

Also, thanks for letting me know that you had to update Rust to compile from source! I will surely include that in the installation instructions portion in the documentation for **NtHiM**, as you have mentioned in your issue #21.

Thanks,
@TheBinitGhimire

**Closed** 2022-01-21 19:43 UTC
Labels: bug
